# Website languages dictionary
langs = {
    "fa":{
        "header":{
            "regular_users": "مشترکین شخصی",
            "enterprise_users": "مشترکین تجاری",
            "shop": "خرید",
            "services": "خدمات",
            "support": "پشتیبانی",
            "my": "آرین تل من",
            "about": "درباره ما",
            "areas": "مناطق تحت پوشش",
            "register": "ثبت نام",
            "login": "ورود کاربری",
            "lang": "EN"
        },
        "footer":{
            "about_span": "شرکت ارتباطات آرین تل",
            "about": "به عنوان یکی از شرکت های زیرمجموعه گروه بزرگ آرین با سهامداران ایرانی و خارجی است. این شرکت به‌عنوان دارنده مجوز اپراتور نوین (Full MVNO) تلفن همراه از سازمان تنظیم مقررات و ارتباطات رادیویی، قصد دارد تا در راستای ارزش آفرینی برای مشتریان خود با بکارگیری بهترین فناوریهای ارتباطی و اطلاعاتی و ابداع خلاقانه ترین راهکارهای جامع، محصولات و خدمات خود را با استفاده از پویایی ونوآوری و توجه به اصل مشتری مداری ارایه نماید .",
            "address": "تهران، میدان ونک، خیابان گاندی، کوچه 15، پلاک 17",
            "cra": "سازمان تنظیم مقررات و ارتباطات رادیویی",
            "ito": "سازمان فناوری اطلاعات ایران",
            "tic": "شرکت ارتباطات زیرساخت",
            "ict": "وزارت ارتباطات و فناوری اطلاعات ایران",
        },
        "home":{
            "slider_more": "اطلاعات بیشتر",
            "services_title": "خدمات آرین تل",
            "areas": "مناطق تحت پوشش",
            "data_fees": "تعرفه مصرف آزاد دیتا و اینترنت",
            "charge_payment": "روش های شارژ و پرداخت",
            "ussd": "کد های دستوری آسان",
            "cooperate": "همکاری با ما",
            "support": "فروش و پشتیبانی ۲۴-۷",
            "organized_solutions": "راهکاری های سازمانی",
            "branches": "نمایندگی",
            "tabs":{
                "cards": "سیم کارت",
                "offers": "بسته ها",
                "promotions": "پیشنهادات"
            }
        },
        "product":{
            "pre_title": "سیم کارت ",
            "introduction": "معرفی محصول",
            "manual": "روش های خرید و استفاده",
            "fees": "تعرفه ها",
            "order": "ثبت نام و خرید"
        },
        "news":{
            "title": "اخبار",
            "read": "ادامه",
            "views": " :تعداد بازدید"
        },
        "packages":{
            "card_type_title": "مناسب برای",
            "postpaid": "سیم کارت های دائمی",
            "prepaid": "سیم کارت های اعتباری",
            "offer_types_title": "انواع بسته ها",
            "hourly": "ساعتی",
            "one_day": "1 روزه",
            "three_days": "3 روزه",
            "seven_days": "7 روزه",
            "fifteen_days": "15 روزه",
            "thirty_days": "30 روزه",
            "sixty_days": "60 روزه",
            "ninty_days": "90 روزه",
            "hundredandtwenty_days": "120 روزه",
            "half_year": "180 روزه",
            "full_year": "365 روزه",
            "special_dur": "زمانی خاص",
            "size_title": "انتخاب حجم",
            "less_than_onehundred": "کمتر از 100 مگابایت",
            "b_one_and_five_hundred": "100 مگابایت تا 500 مگابایت",
            "b_five_hundred_and_two_gigabytes": "500 مگابایت تا 2 گیگابایت",
            "b_two_and_ten_gigabytes": "2 گیگابایت تا 10 گیگابایت",
            "more_than_ten_gigabytes": "بیشتر از 10 گیگابایت",
            "unlimited": "نامحدود",
            "sell_button": "خرید آنلاین",
            "currency": "ریال"
        },
        "employments":{
            "title": "همکاری با ما",
            "description": "ما اعتقاد داریم سرمایۀ اصلی هر سازمان، نیروی انسانی آن است. جذبِ افراد متخصص و کوشا در سرلوحه اهداف این شرکت قرار دارد. بنابراین از تمام علاقه‌مندان به حضور در شرکت ارتباطات آرین تل ، دعوت می‌کنیم تا به جمع ما بپیوندند. ما چشم‌ به راه حضور افراد توانمند و خلاق هستیم و زمینه‌های لازم را برای فعالیت این افراد را فراهم کرده‌ایم. لطفا فایل رزومه خود را (فرمت pdf) به همراه یک قطعه عکس به آدرس ایمل info@ariyantel.ir  ارسال و یا فرم زیر را تکمیل نمایید.",
            "first_name": "نام",
            "last_name": "نام خانوادگی",
            "national_code": "کد ملی",
            "education": "سطح تحصیلات",
            "field": "رشته تحصیلی",
            "phone": "شماره موبایل",
            "military_service_status": "وضعیت نظام وظیفه",
            "ups_record": "سابقه کاری در زمینه یو پی اس",
            "cooperate_type": "نوع همکاری (فروش/پشتیبانی)",
            "cooperate_date": "تاریخ همکاری (سال)",
            "company": "نام شرکت",
            "resume": "آپلود رزومه",
            "captcha": "متن کنترلی",
            "submit": "ارسال",
        },
        "enterprise":{
            "internet": "اینترنت پرسرعت سازمانی",
            "connections": "ارتباطات سازمانی",
            "cooperate": "فرصت مشارکت و همکاری"
        }
    },
    "en":{
        "header":{
            "regular_users": "Personal Users",
            "enterprise_users": "Business Users",
            "shop": "Shop",
            "services": "Services",
            "support": "Support",
            "my": "My ArianTel",
            "about": "About Us",
            "areas": "Coverage Maps",
            "register": "Signup",
            "login": "Login",
            "lang": "FA"
        },
        "footer":{
            "about_span": "ArianTel",
            "about": "el is one of the subsidiaries of Arian Group with Iranian and foreign shareholders. The company, as the holder of a new mobile operator (Full MVNO) license from the Radio Regulatory Authority, intends to create value for its customers by using the best communication and information technologies and inventing the most creative comprehensive solutions, products and services. Using dynamism and innovation and paying attention to the principle of customer orientation.",
            "address": "ArianTel Head Office: Tehran, Gandi St., 15th St., No. 17, First Floor",
            "cra": "Communication Regulatory Authority (CRA)",
            "ito": "Information Technology Organization",
            "tic": "Telecommunication Infrastructure Company",
            "ict": "Information and Communication Technology Ministry",
        },
        "home":{
            "slider_more": "More",
            "services_title": "َAriantel Services",
            "areas": "Coverage Maps",
            "data_fees": "Tariff Plans",
            "charge_payment": "Payment Methods",
            "ussd": "USSD Codes",
            "cooperate": "Employments",
            "support": "24/7 Support",
            "organized_solutions": "Business Solutions",
            "branches": "Agencies",
            "tabs":{
                "cards": "Sim Card",
                "offers": "Offers",
                "promotions": "Promotions"
            }
        },
        "product":{
            "pre_title": "",
            "introduction": "Introduction",
            "manual": "How To Buy And Use",
            "fees": "Fees",
            "order": "Sign Up & Order"
        },
        "news":{
            "title": "News",
            "read": "Read",
            "views": "Views: "
        },
        "packages":{
            "card_type_title": "For",
            "postpaid": "Postpaid Sim Cards",
            "prepaid": "Prepaid Sim Cards",
            "offer_types_title": "Offer Types",
            "hourly": "hourly",
            "one_day": "1 Day",
            "three_days": "3 Days",
            "seven_days": "7 Days",
            "fifteen_days": "15 Days",
            "thirty_days": "30 Days",
            "sixty_days": "60 Days",
            "ninty_days": "90 Days",
            "hundredandtwenty_days": "120 Days",
            "half_year": "180 Days",
            "full_year": "365 Days",
            "special_dur": "Special",
            "size_title": "Size",
            "less_than_onehundred": "Less than 100MB",
            "b_one_and_five_hundred": "From 100MB to 500MB",
            "b_five_hundred_and_two_gigabytes": "From 500MB to 2GB",
            "b_two_and_ten_gigabytes": "From 2GB to 10GB",
            "more_than_ten_gigabytes": "More than 10GB",
            "unlimited": "Unlimited",
            "sell_button": "Purchase",
            "currency": "Rials"
        },
        "employments":{
            "title": "Employments",
            "description": "We believe that the main asset of any organization is its human resources. Attracting professional and loyal people is at the top of the company's goals. Therefore, we invite all those interested in joining ArianTel to join us. We are the source of capable and creative people and we have provided the necessary enviroment for the activities of these people. Please send your resume in pdf format along with a photo to the email address info@ariantel.ir or fill out the form below",
            "first_name": "Name",
            "last_name": "Last Name",
            "national_code": "Nation Code",
            "education": "Educational Level",
            "field": "Major",
            "phone": "Mobile Number",
            "military_service_status": "Military service status",
            "ups_record": "Work experience in the field of UPS",
            "cooperate_type": "Type of cooperation (sale or support)",
            "cooperate_date": "Date of cooperation (year)",
            "company": "Company Name",
            "resume": "Upload Resume",
            "captcha": "*Control Text",
            "submit": "Submit",
        },
        "enterprise":{
            "internet": "Business Fast Internet",
            "connections": "Business Relations",
            "cooperate": "Opportunity for participation and cooperation"
        }
    },
}
